### ISSUE TITLE
missing data in "Protection Priority" View

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/thinkspatial#2]
currently only the category "very high protection priority" exists and only associated river segments are shown. What about the other categories/data?

**Comment by patrick-cipot** [comment]
It's not a bug, it's a feature: Carina Seliger wrote on 8/10/18:

> - crit_tsz5 = Protection priority (abweichend vom pdf soll nur eine Kategorie dargestellt werden):
> 1 - very high protection priority (blau)
> (2-4 - nicht ausweisen und auch nicht bilanzieren!)

But I can implement the other categories as well if you want.

**Comment by chrisgraf** [comment]
Oh! Danke für die Aufmerksamkeit!

**Comment by chrisgraf** [comment]
Possibly we have to at least show the other river segments, but I will check this today...
